### ISSUE TITLE
Lab 4 - bloom is empty (no 

### ISSUE THREAD

**Issue by Samyouell** [neo4j-partners/hands-on-lab-neo4j-and-vertex-ai#18] opened 2023-02-10 20:24 UTC
Perspective was created during an earlier step, before data is loaded.  Therefore the Perspective is empty.  Students will be confused.
Easiest solution is probably to remove the steps during earlier lab where students connect to Bloom.
2nd solution is to tell students to create/import a new perspective

**Comment by gogitguhan** [comment] 2023-02-12 22:21
Fixed it. Latest version doesn't request login. Bloom will be under the 'Explore' tab. Added a new screenshoot to show the same.

**Comment by benofben** [comment] 2023-02-14 05:48
Thanks Guhan.  I ended up rewriting the entire bloom lab.  The perspective is still coming up empty, even if no one logs in.  I'm having to refresh it.  Curious if you guys have any thoughts on what might be wrong here.

**Comment by benofben** [comment] 2023-02-14 05:55
Closing this issue as it is a duplicate of https://github.com/neo4j-partners/hands-on-lab-neo4j-and-vertex-ai/issues/10

**Closed by benofben** 2023-02-14 05:55 UTC
